#General Site Settings
site_name: 'Smaug Trove Docs'
#site_url: https://docs.smaugstrove.live/
repo_url: https://github.com/untraceablez/smaug-docs
repo_name: untraceablez/smaug-docs

#Theme & Theme Specific Settings
theme:
  logo: img/logo.png
  favicon: img/logo.png
  icon:
    repo: fontawesome/brands/github-alt
  name: material
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.path
  - navigation.footer
  - toc.integrate
  - navigation.top
  - content.code.copy
  - content.code.select
  - content.code.annotate

#Plugins 
plugins:
  - search
  - pdf-export
  - mkdocs-video
  - git-revision-date-localized:
      enable_creation_date: true

#Navigation Layout of Site
nav:
    - 'Introduction': 
      - 'index.md'
    - darrs:
      - 'Radarr': 'darrs/radarr.md' #Radarr Config
      - 'Sonarr': 'darrs/sonarr.md' #Sonarr Config
      - 'Mylar': 'darrs/mylar.md' #Mylar Config
      - 'Prowlarr': 'darrs/prowlarr.md' #Prowlarr Config
      - 'Lidarr': 'darrs/lidarr.md' #Lidarr Config

#Markdown Extensions
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Extra Settings
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/untraceablez
