site_name: 'Smaug Trove Docs'
#site_url: https://docs.smaugstrove.live/
theme:
  name: material
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
plugins:
  - search
  - pdf-export
  - mkdocs-video
nav:
    - 'Introduction': 
      - 'index.md'
    - darrs:
      - 'Radarr': 'darrs/radarr.md' #Radarr Config
      - 'Sonarr': 'darrs/sonarr.md' #Sonarr Config
      - 'Mylar': 'darrs/mylar.md' #Mylar Config
      - 'Prowlarr': 'darrs/prowlarr.md' #Prowlarr Config
      - 'Lidarr': 'darrs/lidarr.md' #Lidarr Config

